# Generated by Django 4.0.5 on 2022-12-07 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_alter_events_invited_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='host',
            field=models.ForeignKey(default='request.user', on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='events',
            name='status',
            field=models.CharField(choices=[('C', 'Completed'), ('P', 'Pending')], max_length=2),
        ),
    ]
