# Generated by Django 4.0.5 on 2022-12-08 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_events_host_alter_events_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='status',
        ),
    ]
