# Generated by Django 4.0.5 on 2022-12-08 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_events_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='invites',
        ),
    ]
