# Generated by Django 4.0.5 on 2022-12-09 11:09

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_delete_invites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.DateField(null=True, validators=[app.models.validate_date]),
        ),
    ]
